language: node_js
node_js:
- "8.11.3"
cache:
  directories:
  - "node_modules"
secure: "moR8syqBuxUK8hn++1Hv67ISFygvJS60EiOlie7ABMYb/jKVOxbskVUTaQ3RvETMjLrCruKv7KW18Cq3jiUvccKj8+eybMpC957lkGq8X11UGOWouCSKG3KMaEZ144SKEeXo6qMVCNo8D9w72wmzqpn34ltAykfw1uGWYxRQl8zv3Wk9lVDdqj4ofZ8EmorKi3xqnQQW00YkhlekoydY7wSuUizZnndP1FvSP5PEzPA0dmB/6Ru8BbqNbdVeNGLws7abN8KXl3cOHMjlsNJci+vLIYG/76IUtByrmAVqLyUHIo6t3r0AxACMoA405094dsr0cjDpmj6xPy8cFKSKONIn4ZPKkGZtO63RMICInS86/Q2W+YpQjhbgpD3NPrXiehvGMDmlCo2bUiAeyH53B3dAEtGY+tlTQKi9QZq0K9QekcGG/+z1bLLn7dJBfjli+dpKfQBcBK8ewmYi+tQfx7dlwt3a0DO229JLAcvY7mCy+Ff4bV5KmgLj3bqGw8xfFRzOiLGGVEDX2EYZf6L3RsLunQGZsygkZV3ztv/8U5MuZspIawpTxNbZaXtVj8BVemwkBbF2LzSR82jHgl6ouYd0kO+ixPp2gxlb8DVMMRMBhfZYGy0tzV8QoxkT00O2HfH90dO6g5xkqOJrx5lMsW4PUg2w4m2AZHplgZpPuH4="
